#!/usr/bin/env bash
# Copyright (c) 2026 The Dash Core developers
# Copyright (c) 2026 The GoByte Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

export LC_ALL=C.UTF-8

set -eo pipefail

SDK_URL="${SDK_URL:-https://bitcoincore.org/depends-sources/sdks}"
SDK_PATH="${SDK_PATH:-depends/SDKs}"
SDK_SOURCES="${SDK_SOURCES:-depends/sdk-sources}"
XCODE_VERSION="${XCODE_VERSION:-26.1.1}"
XCODE_RELEASE="${XCODE_RELEASE:-17B100}"
XCODE_ARCHIVE="Xcode-${XCODE_VERSION}-${XCODE_RELEASE}-extracted-SDK-with-libcxx-headers"
XCODE_AR_HASH="${XCODE_AR_HASH:-9600fa93644df674ee916b5e2c8a6ba8dacf631996a65dc922d003b98b5ea3b1}"
XCODE_AR_PATH="${SDK_SOURCES}/${XCODE_ARCHIVE}.tar"

if [ ! -d "${SDK_PATH}/${XCODE_ARCHIVE}" ]; then
    if [ ! -f "${XCODE_AR_PATH}" ]; then
        echo "Downloading macOS SDK..."
        mkdir -p "${SDK_SOURCES}"
        curl --location --fail "${SDK_URL}/${XCODE_ARCHIVE}.tar" -o "${XCODE_AR_PATH}"
    fi
    echo "Verifying macOS SDK..."
    if [ "$(sha256sum "${XCODE_AR_PATH}" | cut -d' ' -f1)" != "${XCODE_AR_HASH}" ]; then
        echo "ERROR: Checksum mismatch for ${XCODE_AR_PATH}"
        sha256sum "${XCODE_AR_PATH}"
        exit 1
    fi
    echo "Extracting macOS SDK..."
    mkdir -p "${SDK_PATH}"
    tar -C "${SDK_PATH}" -xf "${XCODE_AR_PATH}"
fi
